spec: flatprofiles
spec_version: "2.0.0"

data:
  model_profiles:
    default:
      provider: openai
      name: gpt-5-mini
      temperature: 1.0
    creative:
      provider: openai
      name: gpt-5-mini
      temperature: 1.0
    fast:
      provider: openai
      name: gpt-5-mini
      temperature: 1.0
  default: default
